#!/bin/bash

server="${USER}-server@127.0.0.1"

elixir --name ${USER}-client@127.0.0.1 \
       --cookie ${USER}-cookie \
       --erl '-kernel inet_dist_listen_min 50000' \
       --erl '-kernel inet_dist_listen_max 60000' \
       -S mix run lib/client.exs "$server" "$@"
